name: deploy

on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update Server Repo
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.APOLLO_KEY }}
        HOST: ${{ secrets.APOLLO_HOST }}
        USER: ${{ secrets.APOLLO_USER }}
      with:
        args: |
          echo $APOLLO_KEY
          echo $APOLLO_HOST
          echo $APOLLO_USER
          cd apollo
          git pull
